#ifndef __KBLOCK_H__
#define  __KBLOCK_H__

enum BLKTRACE_TYPE {
	BLKTRACE_RQ_INSERT,
	BLKTRACE_DIRTY_PAGES,
	BLKTRACE_BIO_BACKMERGE,
	BLKTRACE_BIO_COMPLETE,
	BLKTRACE_BIO_QUEUE,
	BLKTRACE_RQ_COMPLETE,
	BLKTRACE_RQ_INSERT,
	BLKTRACE_RQ_REQUEUE,
};

enum IOCTL_USEKBLOCK_SUB{
	IOCTL_USEKBLOCK_NONE = 0,
	IOCTL_USEKBLOCK_TRACE,
};

struct kblock_ioctl {
	int enable;
	int subtype;
	int trace_bits;
};

#endif

